#!/bin/bash

./node_modules/sass/sass.js --no-source-map --quiet-deps --load-path=node_modules/govuk-frontend/dist --load-path=node_modules/@ministryofjustice/frontend --load-path=node_modules/govuk-elements-sass/public/sass --load-path=node_modules/govuk_frontend_toolkit/stylesheets --load-path=.  app/assets/sass/application.scss app/public/stylesheets/application.css
