module.exports = {
  LOGGING_PATH: process.env.LOGGING_PATH,
  // DB
  DATABASE_SERVER: process.env.APVS_DATABASE_SERVER,
  DATABASE: process.env.APVS_DATABASE,
  INT_WEB_USERNAME: process.env.APVS_INT_WEB_USERNAME,
  INT_WEB_PASSWORD: process.env.APVS_INT_WEB_PASSWORD,
  INT_MIGRATION_USERNAME: process.env.APVS_INT_MIGRATION_USERNAME,
  INT_MIGRATION_PASSWORD: process.env.APVS_INT_MIGRATION_PASSWORD,

  // File upload
  FILE_UPLOAD_LOCATION: process.env.FILE_UPLOAD_LOCATION || './uploads'
}
