module.exports = {
  ACCEPT_CLAIM_NOTIFICATION: 'ACCEPT-CLAIM-NOTIFICATION',
  REJECT_CLAIM_NOTIFICATION: 'REJECT-CLAIM-NOTIFICATION',
  REQUEST_INFORMATION_CLAIM_NOTIFICATION: 'REQUEST-INFORMATION-CLAIM-NOTIFICATION',
  UPDATED_CONTACT_DETAILS_CLAIM_NOTIFICATION: 'UPDATED-CONTACT-DETAILS-CLAIM-NOTIFICATION'
}
