# Environment specific values, override helm_deploy/help-with-prison-visits-internal/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "manage.hwpv-preprod.hmpps.service.justice.gov.uk"

  env:
    APVS_MOJ_SSO_REDIRECT_URI: 'https://manage.hwpv-preprod.hmpps.service.justice.gov.uk/login/callback'
    APVS_MOJ_SSO_TOKEN_HOST: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth'
    APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits-preprod.hmpps.service.justice.gov.uk'
    HWPV_COOKIE_DOMAIN: "manage.hwpv-preprod.hmpps.service.justice.gov.uk"
    HWPV_POST_LOGOUT_URL: "https://manage.hwpv-preprod.hmpps.service.justice.gov.uk/"
    HWPV_COOKIE_NAME: hwpv-session-preprod

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits-devtest
