---
# Environment specific values, override helm_deploy/help-with-prison-visits-internal/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "caseworker.help-with-prison-visits.service.gov.uk"
    tlsSecretName: "help-with-prison-visits-caseworker-cert"

  env:
    APVS_MOJ_SSO_REDIRECT_URI: 'https://caseworker.help-with-prison-visits.service.gov.uk/login/callback'
    APVS_MOJ_SSO_TOKEN_HOST: 'https://sign-in.hmpps.service.justice.gov.uk/auth'
    MANAGE_USERS_API_URL: 'https://manage-users-api.hmpps.service.justice.gov.uk'
    APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits.service.gov.uk'
    HWPV_COOKIE_DOMAIN: "caseworker.help-with-prison-visits.service.gov.uk"
    HWPV_POST_LOGOUT_URL: "https://caseworker.help-with-prison-visits.service.gov.uk/"
    HWPV_COOKIE_NAME: hwpv-session-prod

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits 
